config/routes.rb
Rails.application.routes.draw do
  get 'admin/dashboard'
  devise_for :admins, controllers: {
    registrations: "registrations",
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Post action for the contact form in home controller
  post "/home/lead", to: "home#create_lead", as: :create_lead
  # Post action for the newsletter form in home controller
  post "/home/newsletter", to: "home#create_newsletter", as: :create_newsletter

  # Defines the root path route ("/")
  root "home#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable :registerable, and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Returns true if no admins have been registered yet, false otherwise.
  def self.registration_allowed?
    Admin.count == 0
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lead.rb
class Lead < ApplicationRecord
  before_save :format_phone_number

  private

  # Reformat phone number to (123) 456-7890 from whatever the user entered
  def format_phone_number
    self.phone = self.phone.gsub(/\D/, '').insert(0, '(').insert(4, ') ').insert(9, '-')
  end
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin
  def dashboard
    @newsletters = Newsletter.all
    @leads = Lead.all
  end

  # action to only allow admins
  def authenticate_admin
    if !admin_signed_in?
      flash[:alert] = "Admin only."
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # get /home
  def home; end

  # POST /home/newsletter
  # Create a newsletter from the home page
  def create_newsletter
    @newsletter = Newsletter.new(newsletter_params)

    if newsletter_params[:pp_check] == "0" || newsletter_params[:pp_check] == false
      redirect_to root_path, alert: "Please check the privacy policy"
    else
      respond_to do |format|
        if @newsletter.save
          format.html { redirect_to root_path, notice: "Thank you for signing up!" }
        else
          format.html { redirect_to root_path, alert: "Failed to sign up: #{@newsletter.errors.full_messages.join(', ')}" }
        end
      end
    end
  end

  # POST /landing/lead
  # # Create a lead from the landing page
  def create_lead
    @lead = Lead.new(lead_params)

    if lead_params[:pp_check] == "0" || lead_params[:pp_check] == false
      redirect_to root_path, alert: "Please check the privacy policy"
    else
      respond_to do |format|
        if @lead.save
          format.html { redirect_to root_path, notice: "We will reach out soon!" }
        else
          format.html { redirect_to root_path, alert: "Failed to sign up: #{@lead.errors.full_messages.join(', ')}" }
        end
      end
    end
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  # This is especially important for the form that is publicly accessible.
  def lead_params
    params.require(:lead).permit(:first_name,
                                  :last_name,
                                  :email,
                                  :phone,
                                  :city,
                                  :state,
                                  :pp_check)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  # This is especially important for the form that is publicly accessible.
  def newsletter_params
    params.require(:newsletter).permit( :email, :pp_check)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :check_registration_allowed, only: [:new, :create]

  private

  # Check if registration is allowed.
  #
  # Redirects to the root page and flashes an alert if registration is not allowed.
  def check_registration_allowed
    unless Admin.registration_allowed?
      flash[:alert] = "Registration is not allowed"
      redirect_to root_path
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/dashboard.html.erb
<div class="flex flex-col justify-center items-center w-full text-gray-200 bg-slate-900 mt-20 min-h-[calc(100vh-88px)]">
  <h1 class="font-bold text-4xl">Admin#dashboard</h1>
  <p>Find me in app/views/admin/dashboard.html.erb</p>
  <div class="grid grid-cols-2 gap-2 mt-6">
    <div>
      <ul>
        <h2 class="text-xl font-bold">Newsletter</h2>
        <% @newsletters.each do |news| %>
          <li class="border border-gray-200 rounded px-2 py-1"><%= news.email %></li>
        <% end %>
      </ul>
    </div>
    <div>
      <ul>
        <h2 class="text-xl font-bold">Leads</h2>
        <% @leads.each do |lead| %>
          <div class="border border-gray-200 rounded px-2 py-1">
            <div class="flex">
              <li class="pe-1"><%= lead.first_name %></li>
              <li><%= lead.last_name %></li>
            </div>
            <li><%= lead.email %></li>
            <li><%= lead.phone %></li>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/home/_leadform.html.erb
<%= form_with scope: :lead, url: create_lead_path, method: "post", class: "max-w-sm mx-auto" do |f| %>
  <div class="flex flex-col sm:flex-row w-full">
    <div class="mb-5 text-start mr-1">
      <div class="flex">
        <%= f.label :first_name, "First Name", for: "first_name", class: "block mb-2 text-sm font-medium text-white" %>
        <span class="text-orange-300 pl-2">*</span>
      </div>
      <%= f.text_field :first_name, id: "first_name", placeholder: "John", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
    </div>
    <div class="mb-5 text-start ml-1">
      <div class="flex">
        <%= f.label :last_name, "Last Name", for: "last_name", class: "block mb-2 text-sm font-medium text-white" %>
        <span class="text-orange-300 pl-2">*</span>
      </div>
      <%= f.text_field :last_name, id: "last_name", placeholder: "Smith", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
    </div>
  </div>
  <div class="mb-5 text-start">
    <div class="flex">
      <%= f.label :lead_email, "Email", for: "lead_email", class: "block mb-2 text-sm font-medium text-white" %>
      <span class="text-orange-300 pl-2">*</span>
    </div>
    <%= f.email_field :email, id: "lead_email", placeholder: "name@example.com", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
  </div>
  <div class="mb-5 text-start">
    <div class="flex">
      <%= f.label :phone, "Phone", for: "phone", class: "block mb-2 text-sm font-medium text-white" %>
      <span class="text-orange-300 pl-2">*</span>
    </div>
    <%= f.text_field :phone, id: "phone", placeholder: "555 888 1234", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
  </div>
  <div class="mb-5 text-start">
    <div class="flex">
      <%= f.label :city, "City", for: "city", class: "block mb-2 text-sm font-medium text-white" %>
      <span class="text-orange-300 pl-2">*</span>
    </div>
    <%= f.text_field :city, id: "city", placeholder: "Chicago", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
  </div>
  <div class="mb-5 text-start">
    <div class="flex">
      <%= f.label :state, "State", for: "state", class: "block mb-2 text-sm font-medium text-white" %>
      <span class="text-orange-300 pl-2">*</span>
    </div>
    <%= f.text_field :state, id: "state", placeholder: "IL", autocomplete: "off", class: " border text-sm rounded-lg block w-full p-2.5 bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-blue-500 focus:border-blue-500" %>
  </div>
  <div class="mx-auto max-w-screen-sm text-xs text-left text-gray-300">
    <%= f.check_box :pp_check, checked: true, 'aria-label' => "privacy policy"  %>&nbsp; I agree with the privacy policy.
  </div>
  <div class="text-xs text-orange-300 text-left pt-2">* Must agree to privacy policy for services *</div>
  <%= f.submit "Send", class: "text-white focus:ring-4 focus:outline-none font-medium rounded-lg text-sm w-full sm:w-auto mt-4 px-8 py-3 text-center bg-blue-600 hover:bg-blue-700 focus:ring-blue-800 cursor-pointer" %>
<% end %>

app/views/home/_newsletter.html.erb
<%= form_with scope: :newsletter, url: create_newsletter_path, class: "max-w-sm mx-auto" do |f| %>
  <div class="items-center mx-auto mb-3 space-y-4 max-w-screen-sm sm:flex sm:space-y-0">
    <div class="relative w-full">
      <label for="email_news" class="hidden mb-2 text-sm font-medium text-gray-300">Email address</label>
      <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
        <svg class="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"></path><path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"></path></svg>
      </div>
      <%= f.email_field :email, id: "email_news", placeholder: "Enter your email", autocomplete: "off", class: "block py-3 pl-10 w-full text-sm rounded-lg border sm:rounded-none sm:rounded-l-lg bg-gray-700 border-gray-600 placeholder-gray-400 text-white focus:ring-primary-500 focus:border-primary-500" %>
    </div>
    <div>
      <%= f.submit "Subscribe", class: "text-white py-3 px-6 w-full text-sm font-medium text-center rounded-lg border cursor-pointer sm:rounded-none sm:rounded-r-lg bg-primary-600 hover:bg-primary-700 focus:ring-primary-800" %>
    </div>
  </div>
  <div class="mx-auto max-w-screen-sm text-xs text-left text-gray-300">
    <%= f.check_box :pp_check, checked: true, 'aria-label' => "privacy policy" %>&nbsp; I agree with the privacy policy.
  </div>
  <div class="text-xs text-orange-300 text-left pt-1">
    * Must agree to privacy policy to recieve Newsletters *
  </div>
<% end %>

app/views/home/index.html.erb
<!--hero-->
<section id="hero" class="mt-14 w-full min-h-svh bg-zinc-950 bg-no-repeat bg-center bg-cover bg-[url('https://images.stockcake.com/public/8/a/6/8a6f2733-82ab-4ac8-97a2-799f740287ac/truck-sunset-drive-stockcake.jpg')]">
  <div class="flex justify-center items-center py-8 px-4 w-full min-h-svh lg:py-16 z-10 relative">
    <div class="flex flex-col justify-center items-center lg:w-fit text-center md:mt-44 lg:mt-60 bg-gray-900/60 px-2 py-5 rounded-lg">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-black mb-5 text-teal-400 text-base md:text-lg rounded-lg inline-block max-w-sm" id="notice"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="py-2 px-3 bg-black mb-5 text-rose-400 text-base md:text-lg rounded-lg inline-block max-w-sm" id="alert"><%= alert %></p>
      <% end %>
      <span class="mb-1 text-2xl font-semibold tracking-tight leading-none md:text-2xl lg:text-4xl text-gray-200">
        Steer your career in the right direction.
      </span>
      <div class="flex flex-col justify-center items-center w-11/12">
        <h1 class="text-3xl font-bold m-0 p-0 text-gray-200">TRUCKERJOBS4U</h1>
      </div>
      <%= link_to "START YOUR JOURNEY", "#contact", class: "py-6 px-12 mt-6 rounded bg-yellow-300 text-slate-900 hover:bg-yellow-400 cursor-pointer font-bold" %>
    </div>
  </div>
</section>
<!--newsletter-->
<section id="newsletter" class="w-full bg-gray-900">
  <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6 z-10">
    <div class="mx-auto max-w-screen-md sm:text-center">
      <h2 class="mb-4 text-3xl tracking-tight font-extrabold sm:text-4xl text-yellow-300">Stay up to date with our newsletter</h2>
      <p class="mx-auto mb-8 max-w-2xl font-light md:mb-12 sm:text-xl text-gray-400">Transportation is changing. Sign up to get the latest news on developments!</p>
      <%= render "newsletter" %>
    </div>
  </div>
</section>
<!--Paths to choose-->
<section id="paths" class="flex justify-center items-center w-full">
  <div class="w-full lg:max-w-4xl my-10 p-4 text-center border rounded-lg shadow sm:p-8 bg-gray-800 border-gray-700">
    <div class="flex justify-center items-center">
      <h1 class="font-bold text-xl text-gray-200">TRUCKERJOBS4U</h1>
    </div>
    <p class="mb-5 text-base sm:text-lg text-gray-400">
      Which route would you prefer? <br/>
      Fill out a quick form, letting our recruiters know a bit about you and what you are looking for or have you found a job and are ready to get serious about seeing what's over the horizon?
    </p>
    <div class="md:grid-cols-3 items-center justify-center space-y-4 sm:flex sm:space-y-0 sm:space-x-4 rtl:space-x-reverse">
      <!--Inquiry Card-->
      <div class="md:w-1/3 md:max-h-[700px] border rounded-lg shadow bg-gray-800 border-gray-700">
        <%= image_tag("https://images.stockcake.com/public/d/1/e/d1e3f8ff-88bd-41c5-b399-25acbdb61107/sunset-truck-interior-stockcake.jpg", width: "480", alt: "View of the truck driver seat at sunset.", class: "rounded-t-lg", loading: "lazy") %>
        <div class="p-5">
          <span class="mb-2 text-2xl font-bold tracking-tight text-white">Quick Inquiry</span>
          <p class="mb-3 font-normal text-gray-400">Just starting to look around for better opportunities? We can help?</p>
          <%= link_to "#contact", class: "inline-flex items-center px-6 py-3 text-sm font-medium text-center text-white rounded-lg focus:ring-4 focus:outline-none bg-blue-600 hover:bg-blue-700 focus:ring-blue-800" do %>
            Help Me
            <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
            </svg>
          <% end %>
        </div>
      </div>
      <!--Application Card-->
      <div class="md:w-1/3 md:max-h-[700px] border rounded-lg shadow bg-gray-800 border-gray-700">
        <%= image_tag("https://images.stockcake.com/public/c/2/b/c2bdfe31-457e-48cc-8e38-8edf98fab29a/sunset-truck-stop-stockcake.jpg", width: "480", alt: "White Kenworth with red stripes in yard under red evening sky.", class: "rounded-t-lg", loading: "lazy") %>
        <div class="p-5">
          <span class="mb-2 text-2xl font-bold tracking-tight text-white">Application</span>
          <p class="mb-3 font-normal text-gray-400">Have you been asked to fill out a application? Get yourself square here.</p>
          <%= link_to root_path, class: "inline-flex items-center px-6 py-3 text-sm font-medium text-center text-white rounded-lg focus:ring-4 focus:outline-none bg-blue-600 hover:bg-blue-700 focus:ring-blue-800" do %>
            Let's Go!
            <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
            </svg>
          <% end %>
        </div>
      </div>
      <!--Job Search Card-->
      <div class="md:w-1/3 md:max-h-[700px] border rounded-lg shadow bg-gray-800 border-gray-700">
        <%= link_to root_path do %>
          <%= image_tag("https://images.stockcake.com/public/9/4/4/944a3f74-7e76-4600-9e8d-d12dffc0fd7f/sunset-truck-journey-stockcake.jpg", width: "480", alt: "Trucks lined up at the wharehouse as the sun rises.", class: "rounded-t-lg", loading: "lazy") %>
          <div class="p-5">
            <span class="mb-2 text-2xl font-bold tracking-tight text-white">Job Search</span>
            <p class="mb-3 font-normal text-gray-400">Want to browse the jobs we are currently placeing driver for? Drive Safe.</p>
            <%= link_to root_path, class: "inline-flex items-center px-6 py-3 text-sm font-medium text-center text-white rounded-lg focus:ring-4 focus:outline-none bg-blue-600 hover:bg-blue-700 focus:ring-blue-800" do %>
              Find it!
              <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
              </svg>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>
<!--contact-->
<section id="contact" class="w-full pt-10 bg-zinc-950">
  <div class="flex flex-col justify-center items-center">
    <div class="w-full lg:max-w-4xl my-10 p-4 text-center border rounded-lg shadow sm:p-8 bg-gray-900 border-gray-700">
      <div class="grid sm:grid-cols-2">
        <div class="hidden md:block mx-auto my-auto">
          <%= image_tag("https://images.stockcake.com/public/d/1/e/d1e3f8ff-88bd-41c5-b399-25acbdb61107/sunset-truck-interior-stockcake.jpg", alt: "View of the truck drivers seat at dusk.", class: "rounded-lg w-72 sm:w-full", loading: "lazy") %>
        </div>
        <div class="flex flex-col justify-center items-center">
          <div class="w-full lg:max-w-xl p-6 space-y-8 sm:p-8 rounded-lg lg:ml-6">
            <h2 class="flex flex-col text-2xl font-bold text-white">
              Contact Us.
            </h2>
            <div class="flex flex-col">
              <small class="text-white">
                Are you ready to jump in the driver's seat of your career? We would love to hear from you. Let's get to work on your new career today!
              </small>
              <small class="text-gray-300">
                [<span class="text-orange-300"> * </span>] indicates required
              </small>
            </div>
            <%= render "leadform" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_alert.html.erb
<!--
//? this is the alert partial
-->
<span class="text-red-700 font-bold bg-red-100 rounded p-4 border-white">
  <%= alert %>
</span>

app/views/layouts/_footer.html.erb
<!-- //? Footer -->
<div class="w-full px-12 bg-black text-slate-100" >
  <nav class="flex flex-col-reverse sm:flex-row justify-evenly items-center p-4">
    <div class="flex flex-col">
      <%= link_to root_path, class: "flex max-w-64" do %>
        <h1>TRUCKERJOBS4U</h1>
      <% end %>
      <span class="flex"><small>TRUCKERJOBS4U.com &#169 Copywrite 2024</small></span>
    </div>
    <div class="flex flex-row justify-evenly w-full">
      <%= link_to root_path, class: "flex items-center text-sm text-gray-400 my-4 px-4 py-3" do %>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7h1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h11.5M7 14h6m-6 3h6m0-10h.5m-.5 3h.5M7 7h3v3H7V7Z"/>
        </svg>
        <span class="ml-1">Blog</span>
      <% end %>
      <%= link_to root_path + "#contact", class: "flex items-center text-sm text-gray-400 my-4 px-4 py-3" do %>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="m3.5 5.5 7.893 6.036a1 1 0 0 0 1.214 0L20.5 5.5M4 19h16a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1Z"/>
        </svg>
        <span class="ml-1">Contact</span>
      <% end %>
    </div>
  </nav>
</div>

app/views/layouts/_navbar.html.erb
<!-- //? Sticky Top Navbar -->
<div class="fixed top-0 z-50 w-full">
  <nav class="relative flex justify-between items-center p-4 h-20 bg-gray-900 text-gray-100">
    <div class="flex justify-evenly items-center w-full">
      <!-- //? Left section links home -->
      <div class="flex justify-center items-center ms-4">
        <%= link_to root_path do %>
          <h1 class="font-bold">TRUCKERJOBS4U</h1>
        <% end %>
      </div>
      <!-- //? Right section Page Links -->
      <div class="flex flex-grow justify-end items-center me-4">
        <ul class="flex space-x-2">
          <li class="hidden md:flex"><%= link_to "Blog", root_path %></li>
          <li class="hidden md:flex"><%= link_to "Contact", root_path + "#contact" %></li>
          <% if admin_signed_in? %>
            <li class="list-none">
              <%= link_to destroy_admin_session_path, data: { turbo_method: :delete } do %>
                <svg class="w-6 h-6 text-green-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                  <path fill-rule="evenodd" d="M12 20a7.966 7.966 0 0 1-5.002-1.756l.002.001v-.683c0-1.794 1.492-3.25 3.333-3.25h3.334c1.84 0 3.333 1.456 3.333 3.25v.683A7.966 7.966 0 0 1 12 20ZM2 12C2 6.477 6.477 2 12 2s10 4.477 10 10c0 5.5-4.44 9.963-9.932 10h-.138C6.438 21.962 2 17.5 2 12Zm10-5c-1.84 0-3.333 1.455-3.333 3.25S10.159 13.5 12 13.5c1.84 0 3.333-1.455 3.333-3.25S13.841 7 12 7Z" clip-rule="evenodd"/>
                </svg>
              <% end %>
            </li>
          <% else %>
            <li class="list_none">
              <%= link_to new_admin_session_path do %>
                <svg class="w-6 h-6 text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm0 0a8.949 8.949 0 0 0 4.951-1.488A3.987 3.987 0 0 0 13 16h-2a3.987 3.987 0 0 0-3.951 3.512A8.948 8.948 0 0 0 12 21Zm3-11a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z"/>
                </svg>
              <% end %>
            </li>
          </li>
        <% end %>
      </ul>
      <button class="md:hidden pb-1 w-6" role="button" aria-label="menu">
        &#9776
      </button>
    </div>
  </div>
</nav>
<!-- //? Dropdown menu - mobile -->
<nav class="hidden bg-white absolute w-2/3 right-2 h-80 overflow-y-auto rounded-b-sm">
  <ul class="flex flex-col py-2 px-3">
    <%= link_to root_path do %>
      <li class="flex border p-2 my-1 rounded-sm">Blog</li>
    <% end %>
    <%= link_to root_path + "#contact" do %>
      <li class="flex border p-2 my-1 rounded-sm">Contact</li>
    <% end %>
  </ul>
</nav>
</div>

app/views/layouts/_notice.html.erb
<!--
//? this is the notice partial
-->
<span class="text-blue-700 font-bold bg-blue-100 rounded p-4 border-white">
  <%= alert %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hmm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-black">
    <header class="">
      <%= render "layouts/navbar" %>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>